name: Translate YouTube Metadata

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib openai
          
      - name: Debug Environment
        run: |
          echo "Checking for required files..."
          ls -la
          echo "Python version:"
          python --version
          
      - name: Create oauth2.json
        run: |
          echo "${{ secrets.OAUTH_JSON }}" > oauth2.json
          echo "Created oauth2.json with size:"
          ls -l oauth2.json
          
      - name: Run translator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_VIDEO_ID: ${{ secrets.MY_VIDEO_ID }}
        run: python translate_metadata.py
