name: Translate YouTube Metadata with OpenAI

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC

jobs:
  translate-metadata:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib openai
      
      - name: Create oauth2.json
        run: |
          echo "${{ secrets.OAUTH_JSON }}" > oauth2.json
      
      - name: Run Python script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_VIDEO_ID: ${{ secrets.MY_VIDEO_ID }}
        run: python translate_metadata.py
